FROM node:16-alpine

# Install git and bash for development tools
RUN apk add --no-cache git bash

# Install dependencies and build the project
WORKDIR /app/IrisProfileSiteFrontend

# Copy only package.json and package-lock.json to install dependencies
COPY ./package*.json /app/IrisProfileSiteFrontend/
RUN ls -l /app
RUN ls -l /app/IrisProfileSiteFrontend
RUN npm install

# Expose the development server port
EXPOSE 8080

# Command to run the development server
CMD ["npm", "run", "serve"]
