version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app/IrisProfileSiteFrontend
      - /app/IrisProfileSiteFrontend/node_modules # Prevent overwriting node_modules
    ports:
      - "8080:8080"
    command: npm run serve # Run the development server