server {
    listen 80;
    server_name irisglaze.net www.irisglaze.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name irisglaze.net www.irisglaze.net;

    ssl_certificate /etc/nginx/ssl/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/origin-key.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
